
# 3.2.3 Уход от циклов: обработка данных с применением массивов

## Задание 1

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` из ```12``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте две матрицы размера ```(3,4)``` с порядком следования элементов в стиле С и Fortran. Найдите поэлементное произведение этих матриц, а после - максимальный элемент в полученной матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```25```)



**Решение:**

In [ ]:
import numpy as np

# Устанавливаем seed для воспроизводимости результатов
np.random.seed(1000)

# Создаем случайный целочисленный массив ndarray из 12 элементов, принадлежащих отрезку [0,10]
arr = np.random.randint(0, 11, 12)

# Создаем две матрицы размера (3,4) с порядком следования элементов в стиле С и Fortran
matrix_c = arr.reshape((3, 4), order='C')
matrix_f = arr.reshape((3, 4), order='F')

# Находим поэлементное произведение этих матриц
product = np.multiply(matrix_c, matrix_f)

# Находим максимальный элемент в полученной матрице
max_element = np.max(product)

print(f"Матрица C:\n{matrix_c}")
print(f"Матрица F:\n{matrix_f}")
print(f"Поэлементное произведение:\n{product}")
print(f"Максимальный элемент: {max_element}")

Матрица C:
[[ 3  7  7  0]
 [ 1  0  9  8]
 [ 9  4 10 10]]
Матрица F:
[[ 3  0  9  4]
 [ 7  1  8 10]
 [ 7  0  9 10]]
Поэлементное произведение:
[[  9   0  63   0]
 [  7   0  72  80]
 [ 63   0  90 100]]
Максимальный элемент: 100


## Задание 2

**Условие:**
Создайте ```3``` случайных целочисленных массива ```ndarray``` размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте из данных массивов один трехмерный массив. Найдя размер полученного массива, вычислите количество элементов в нем. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```56```)


**Решение:**

In [ ]:
import numpy as np

np.random.seed(1000)  # Задаем seed для воспроизводимости

# Создаем 3 случайных целочисленных массива размера (10, 10) из элементов от 0 до 10
arr1 = np.random.randint(0, 11, size=(10, 10))
arr2 = np.random.randint(0, 11, size=(10, 10))
arr3 = np.random.randint(0, 11, size=(10, 10))

# Объединяем данные массивы в трехмерный массив
array_3d = np.stack([arr1, arr2, arr3])

# Находим размер полученного массива
array_size = array_3d.shape

# Вычисляем количество элементов в массиве
num_elements = np.prod(array_size)

print(num_elements)

300


## Задание 3

**Условие:**
С использование методов ```ndarray``` сформируйте массив размера ```(20,2)```, в первом столбце которого идут целые числа, начиная с ```1```,а во втором - первые 20 нечетных чисел, начиная с ```3```. Найдите среднее значение второго столбца.

**Формат ответа:**
Число (например, ```34```)



**Решение:**

In [ ]:
import numpy as np

# Создаем массив размера (20,2)
arr = np.zeros((20, 2))

# В первом столбце идут целые числа, начиная с 1
arr[:, 0] = np.arange(1, 21)

# Во втором столбце - первые 20 нечетных чисел, начиная с 3
arr[:, 1] = np.arange(3, 43, 2)

# Находим среднее значение второго столбца
mean = np.mean(arr[:, 1])

print(f"Массив:\n{arr}")
print(f"Среднее значение второго столбца: {mean}")

Массив:
[[ 1.  3.]
 [ 2.  5.]
 [ 3.  7.]
 [ 4.  9.]
 [ 5. 11.]
 [ 6. 13.]
 [ 7. 15.]
 [ 8. 17.]
 [ 9. 19.]
 [10. 21.]
 [11. 23.]
 [12. 25.]
 [13. 27.]
 [14. 29.]
 [15. 31.]
 [16. 33.]
 [17. 35.]
 [18. 37.]
 [19. 39.]
 [20. 41.]]
Среднее значение второго столбца: 22.0
